In [1]:
from scipy import sparse
import numpy as np

#### 疎行列

要素のほとんどが0の行列。機械学習では疎行列をよく使う。疎行列を効率的に扱うためのクラスにlil_matrixとcsr_matrix, csc_matrixがある。

- lil_matrix ... 簡単に値設定ができるが計算は遅い
- csr_matrix, csc_matrix... 値設定が面倒だが計算は速い

csrはrow方向に圧縮。cscはcolumn方向に圧縮。

In [12]:
a=sparse.lil_matrix((5,5)) #全要素が0の疎行列

In [14]:
a.todense()   #密行列に変換

matrix([[ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.]])

In [10]:
# lil_matrixに値設定
a[0,0]=1
a[1,2]=2
a[3,4]=3
a[4,4]=4

In [11]:
a.todense()

matrix([[ 1.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  2.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  0.],
        [ 0.,  0.,  0.,  0.,  3.],
        [ 0.,  0.,  0.,  0.,  4.]])

In [6]:
b=a.tocsr() #csr_matrixに変換
b

<5x5 sparse matrix of type '<class 'numpy.float64'>'
	with 4 stored elements in Compressed Sparse Row format>

In [7]:
b.getrow(1).todense()

matrix([[ 0.,  0.,  2.,  0.,  0.]])

In [8]:
v=np.array([1,2,3,4,5])
a.dot(v)

array([  1.,   6.,   0.,  15.,  20.])