# データサイエンティスト養成読本のnumpy基礎
numpyの基本的な使い方について学ぶ

In [1]:
import numpy as np
import sympy as sp
sp.init_printing(use_latex="mathjax")

In [2]:
# 2x2の行列を生成
a = np.array([[1,2], [3, 4]])
a

array([[1, 2],
       [3, 4]])

In [3]:
# np.arangeで0~9までの配列を生成
b =np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
# np.reshapeで0-10の配列から、2x5行列に変形
c = b.reshape(2,5)
c

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [5]:
# 1次元配列から2x2行列に変形
a = np.arange(4).reshape(2,2)
print(a)
b = np.arange(3,7).reshape(2,2)
print(b)

[[0 1]
 [2 3]]
[[3 4]
 [5 6]]


In [6]:
# 行列の演算:和
a + b

array([[3, 5],
       [7, 9]])

In [7]:
# 転置行列
a.T

array([[0, 2],
       [1, 3]])

In [8]:
# aの転置行列 とbの和
a.T + b

array([[3, 6],
       [6, 9]])

In [9]:
# 差
a - b

array([[-3, -3],
       [-3, -3]])

In [10]:
#行列A, Bの積
np.dot(a,b)  
# [[0, 1],     [[3, 4],
#  [2, 3]]      [5, 6]]

# [[0*3+1*5, 0*4+1*6],
#  [2*3+3*5, 2*4+3*6]]

array([[ 5,  6],
       [21, 26]])

In [11]:
v=np.array([10, 20])

In [12]:
# 2x2の行列Aと、1x2の行列v
np.dot(a,v)  
# 本来なら、vは2x1に転置しないと積が定義できないが、自動でやってくれる
# ※積は左の行ベクトルの要素数と右の列ベクトル要素数が一致しなければならない
# [[0, 1],     [10,
#  [2, 3]]      20]

# [[0*10+1*20],
#  [2*10+3*20]]

# [20,
#  80]

# 1次元の配列は、行ベクトルまたは列ベクトルの両方を表現する

array([20, 80])

In [13]:
np.dot(v,a)  # 1x2の行列vと、2x2の行列A
# [10, 20]    [[0, 1],
#              [2, 3]]

# [10*0+20*2, 10+1*20*3]

# [40, 70]


array([40, 70])

In [14]:
c = np.arange(16).reshape(4, 4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [15]:
c[1] #インデクシング　行1

array([4, 5, 6, 7])

In [16]:
c[1:3]   #スライシング 行1-2

array([[ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [17]:
c[:,2:4]  #全行x2-3列

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15]])

In [18]:
c[1:3,1:3]  #1-2行, 1-2列

array([[ 5,  6],
       [ 9, 10]])

In [19]:
l = [n % 2 == 0 for n in range(16)]

bidx = np.array(l).reshape(4,4)
bidx  #偶数インデックスだけTrueにする

array([[ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False]], dtype=bool)

In [20]:
c[bidx]

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [21]:
c[c<10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [22]:
c[c%2==0]

array([ 0,  2,  4,  6,  8, 10, 12, 14])

In [23]:
c*2 #ブロードキャスティング（全要素に演算）

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

In [24]:
a=np.arange(6).reshape(2,3)
a

array([[0, 1, 2],
       [3, 4, 5]])

In [25]:
b=np.arange(6,12).reshape(2,3)
b

array([[ 6,  7,  8],
       [ 9, 10, 11]])

In [26]:
np.c_[a,b]   #横に結合

array([[ 0,  1,  2,  6,  7,  8],
       [ 3,  4,  5,  9, 10, 11]])

In [27]:
np.r_[a,b]   #縦に結合

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [28]:
c=np.arange(3)
c

array([0, 1, 2])

In [29]:
d=np.arange(3,6)
d

array([3, 4, 5])

In [30]:
# 行列を横方向に結合 .c_
np.c_[c,d]  #1次元配列が縦ベクトルとして解釈される

array([[0, 3],
       [1, 4],
       [2, 5]])

In [31]:
# 行列を縦方向に結合 .r_
np.r_[c,d]   #1次元配列が縦ベクトルとして解釈される

array([0, 1, 2, 3, 4, 5])

In [32]:
np.add(c,d)

array([3, 5, 7])