In [3]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

In [32]:
array1 = np.array([1,4,5,8], float)
print(array1)
array2 = np.array([[1,2,3], [4,5,6]], float)
print(array2)

[ 1.  4.  5.  8.]
[[ 1.  2.  3.]
 [ 4.  5.  6.]]


In [33]:
array1[2]

5.0

In [34]:
array1[:2]

array([ 1.,  4.])

In [35]:
array2[:]

array([[ 1.,  2.,  3.],
       [ 4.,  5.,  6.]])

In [36]:
array_1 = np.array([[1,2], [3,4]], float)
array_2 = np.array([[5,6], [7,8]], float)
array_1 + array_2

array([[  6.,   8.],
       [ 10.,  12.]])

In [37]:
array_1 - array_2

array([[-4., -4.],
       [-4., -4.]])

In [39]:
array_1 * array_2

array([[  5.,  12.],
       [ 21.,  32.]])

In [50]:
array_1 = np.array([1, 2, 3], float)
array_2 = np.array([[6], [7], [8]], float)

In [51]:
np.mean(array_1)

2.0

In [52]:
np.mean(array_2)

7.0

In [53]:
np.dot(array_1, array_2)

array([ 44.])

In [54]:
1*6 + 2*7 + 3*8

44